#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.1
#  in conjunction with Tcl version 8.6
#    May 12, 2021 09:11:20 AM CEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import HelloWorld_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Main (root)
    HelloWorld_support.init(root, top)
    root.mainloop()

w = None
def create_Main(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Main(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Main (w)
    HelloWorld_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Main():
    global w
    w.destroy()
    w = None

class Main:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("286x151+270+100")
        top.minsize(116, 1)
        top.maxsize(2110, 1418)
        top.resizable(1,  1)
        top.title("Hello World")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.BtnSayHello = tk.Button(top)
        self.BtnSayHello.place(relx=0.35, rely=0.596, height=24, width=77)
        self.BtnSayHello.configure(activebackground="#ececec")
        self.BtnSayHello.configure(activeforeground="#000000")
        self.BtnSayHello.configure(background="#d9d9d9")
        self.BtnSayHello.configure(disabledforeground="#a3a3a3")
        self.BtnSayHello.configure(font="-family {Segoe UI} -size 9")
        self.BtnSayHello.configure(foreground="#000000")
        self.BtnSayHello.configure(highlightbackground="#d9d9d9")
        self.BtnSayHello.configure(highlightcolor="black")
        self.BtnSayHello.configure(pady="0")
        self.BtnSayHello.configure(text='''Say Hello''')
        self.BtnSayHello.bind('<ButtonRelease-1>',lambda e:HelloWorld_support.BtnSayHello(e))

        self.TextHello = tk.Label(top)
        self.TextHello.place(relx=0.245, rely=0.199, height=21, width=134)
        self.TextHello.configure(background="#d9d9d9")
        self.TextHello.configure(disabledforeground="#a3a3a3")
        self.TextHello.configure(font="-family {Segoe UI} -size 9")
        self.TextHello.configure(foreground="#000000")
        self.TextHello.configure(relief="sunken")
        self.TextHello.configure(text='''- - -''')

if __name__ == '__main__':
    vp_start_gui()





