#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.1
#  in conjunction with Tcl version 8.6
#    May 03, 2021 03:29:20 PM CEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def BtnReadRelease(p1):
    import nidaqmx
    import nidaqmx.system
    from nidaqmx.constants import TerminalConfiguration
    import math

# ajoute
    DevName = ""
    for device in nidaqmx.system.System.local().devices:
        if device.product_type.find("USB-600") != -1:
            DevName = device.name
            break

    with nidaqmx.Task() as task:
        try:
            task.ai_channels.add_ai_voltage_chan(DevName+"/ai0:1", "", TerminalConfiguration.RSE)
            ai0, ai1 = task.read()
        except:
            ai0 = math.nan
            ai1 = math.nan

    w.AI0["text"] = "{:.2f}".format(ai0)
    w.AI1["text"] = "{:.2f}".format(ai1)



def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import TestDAQmx
    TestDAQmx.vp_start_gui()
